// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/lta2705/payment-processor/internal/functionality"
	"github.com/lta2705/payment-processor/internal/handler"
	"github.com/lta2705/payment-processor/internal/middleware"
	"github.com/lta2705/payment-processor/internal/repository"
	"github.com/lta2705/payment-processor/internal/service"
	"github.com/lta2705/payment-processor/internal/worker"
	"github.com/lta2705/payment-processor/pkg/config"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	kafkaProducerConfig := config.LoadKafkaProducerConfig()
	writer := middleware.CreateKafkaProducer(kafkaProducerConfig)
	kafkaProducerWorker := worker.NewProducerWorker(writer)
	producer := functionality.NewProduce(kafkaProducerWorker)
	kafkaConsumerConfig := config.LoadKafkaConsumerConfig()
	reader := middleware.CreateKafkaConsumer(kafkaConsumerConfig)
	kafkaConsumerWorker := worker.NewConsumerWorker(reader)
	dbConfig := config.LoadDBConfig()
	db := middleware.SetupDatabase(dbConfig)
	paymentRepository := repository.NewTransactionRepository(db)
	paymentService := service.NewPaymentService(paymentRepository)
	cardPaymentHandler := handler.NewCardPaymentHandler(paymentService)
	qrPaymentHandler := handler.NewQrPaymentHandler(paymentService)
	consumer := functionality.NewConsumer(kafkaConsumerWorker, cardPaymentHandler, qrPaymentHandler)
	app := NewApp(producer, consumer)
	return app, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewTransactionRepository)

var serviceSet = wire.NewSet(service.NewPaymentService)

var handlerSet = wire.NewSet(handler.NewCardPaymentHandler, handler.NewQrPaymentHandler)

var ProducerSet = wire.NewSet(config.LoadKafkaProducerConfig, middleware.CreateKafkaProducer, worker.NewProducerWorker, functionality.NewProduce)

var ConsumerSet = wire.NewSet(config.LoadKafkaConsumerConfig, middleware.CreateKafkaConsumer, worker.NewConsumerWorker, functionality.NewConsumer)

var databaseSet = wire.NewSet(config.LoadDBConfig, middleware.SetupDatabase)
