// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/lta2705/payment-processor/internal/middleware"
	"github.com/lta2705/payment-processor/internal/service"
	"github.com/lta2705/payment-processor/internal/transport"
	"github.com/lta2705/payment-processor/pkg/config"
	"net"
	"os"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	listener, err := ProvideListener()
	if err != nil {
		return nil, err
	}
	sessionManager := NewSessionManager()
	kafkaProducerConfig := config.LoadKafkaProducerConfig()
	writer := middleware.CreateKafkaProducer(kafkaProducerConfig)
	kafkaConsumerConfig := config.LoadKafkaConsumerConfig()
	reader := middleware.CreateKafkaConsumer(kafkaConsumerConfig)
	dbConfig := config.LoadDBConfig()
	db := middleware.SetupDatabase(dbConfig)
	server := transport.NewServer(sessionManager, writer, reader, db)
	app := NewApp(listener, server)
	return app, nil
}

// wire.go:

func ProvideListener() (net.Listener, error) {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8089"
	}
	return net.Listen("tcp", ":"+port)
}

var DatabaseSet = wire.NewSet(config.LoadDBConfig, middleware.SetupDatabase)

var ProducerWorkerSet = wire.NewSet(config.LoadKafkaProducerConfig, middleware.CreateKafkaProducer)

var ConsumerWorkerSet = wire.NewSet(config.LoadKafkaConsumerConfig, middleware.CreateKafkaConsumer, service.NewConsumerWorker)

var sessionSet = wire.NewSet(
	NewSessionManager, wire.Bind(
		new(transport.SessionManager),
		new(*SessionManager),
	),
)

var ServerSet = wire.NewSet(transport.NewServer, transport.NewHandler)
