// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"net"
	"os"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	listener, err := ProvideListener()
	if err != nil {
		return nil, err
	}
	sessionManager := NewSessionManager()
	app := NewApp(listener, sessionManager)
	return app, nil
}

// wire.go:

func ProvideListener() (net.Listener, error) {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8089"
	}
	return net.Listen("tcp", ":"+port)
}
